name: publish

on:
 push:
  branches: ["main"]
 workflow_dispatch:

permissions:
 contents: read

jobs:
 publish :
  runs-on: windows-latest

  steps:
   - name: setup .net
     uses: actions/setup-dotnet@v3
     with: 
      dotnet-version: '4.5'

   - name: Restore 
     run: nuget restore SampleASPFramework45.sln
   - name: Build
     run: msbuild SampleASPFramework45.sln --configuration Release --no-restore

   - name: publish
     run: dotnet publish SampleASPFramework45.sln --configuration Release --no-build

     
       
     
